# Generated by Django 4.1.7 on 2023-03-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0003_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nascionalidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
