# Generated by Django 4.1.7 on 2023-03-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0006_alter_veiculo_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='placas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
