# Generated by Django 4.1.7 on 2023-03-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0007_veiculo_placas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='placas',
            new_name='placa',
        ),
    ]
