# Generated by Django 4.1.7 on 2023-03-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0008_rename_placas_veiculo_placa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name_plural': 'Cores'},
        ),
    ]
